version: "3"

services:

    local_fcgi-server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: local_fcgi-server
        tty: true
        
        
    fcgi-server:
       build: .
       tty: true
       ports:
            - "80:81"
       depends_on:
         - local_fcgi-server
